# -*- coding: utf-8 -*-
"""FuzzyLogicChanged.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zyknWtgr-ZumsWl1DwtN6voFRSH6X6fj
"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt

# ---------------------------------------------------
# 1. Define Input and Output Variables
# ---------------------------------------------------

attendance = ctrl.Antecedent(np.arange(0, 101, 1), 'attendance')
assignments = ctrl.Antecedent(np.arange(0, 101, 1), 'assignments')
participation = ctrl.Antecedent(np.arange(0, 11, 0.1), 'participation')
performance = ctrl.Consequent(np.arange(0, 101, 1), 'performance')

# ---------------------------------------------------
# 2. Define Membership Functions (Adjusted Values)
# ---------------------------------------------------

# Attendance
attendance['poor'] = fuzz.trimf(attendance.universe, [0, 0, 50])
attendance['average'] = fuzz.trimf(attendance.universe, [40, 65, 85])
attendance['excellent'] = fuzz.trimf(attendance.universe, [80, 100, 100])

# Assignments
assignments['weak'] = fuzz.trimf(assignments.universe, [0, 0, 60])
assignments['satisfactory'] = fuzz.trimf(assignments.universe, [50, 70, 85])
assignments['strong'] = fuzz.trimf(assignments.universe, [80, 100, 100])

# Class Participation (0–10 scale)
participation['low'] = fuzz.trimf(participation.universe, [0, 0, 3.5])
participation['medium'] = fuzz.trimf(participation.universe, [3, 5.5, 8])
participation['high'] = fuzz.trimf(participation.universe, [7, 10, 10])

# Performance Output
performance['needs_improvement'] = fuzz.trimf(performance.universe, [0, 0, 40])
performance['satisfactory'] = fuzz.trimf(performance.universe, [30, 55, 70])
performance['good'] = fuzz.trimf(performance.universe, [65, 80, 90])
performance['excellent'] = fuzz.trimf(performance.universe, [85, 100, 100])

# ---------------------------------------------------
# 3. Define Rules (Cleaner version)
# ---------------------------------------------------

rule1 = ctrl.Rule(
    attendance['poor'] | assignments['weak'] | participation['low'],
    performance['needs_improvement']
)

rule2 = ctrl.Rule(
    attendance['average'] & assignments['satisfactory'] & participation['medium'],
    performance['satisfactory']
)

rule3 = ctrl.Rule(
    attendance['excellent'] & assignments['satisfactory'] & participation['high'],
    performance['good']
)

rule4 = ctrl.Rule(
    attendance['excellent'] & assignments['strong'] & participation['high'],
    performance['excellent']
)

rule5 = ctrl.Rule(
    attendance['average'] & assignments['weak'] & participation['medium'],
    performance['needs_improvement']
)

rule6 = ctrl.Rule(
    attendance['excellent'] & assignments['strong'] & participation['medium'],
    performance['good']
)

# ---------------------------------------------------
# 4. Build Simulation System
# ---------------------------------------------------

performance_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6])

def evaluate_student(att_score, assign_score, part_score):
    """Compute fuzzy performance for a student."""

    sim = ctrl.ControlSystemSimulation(performance_ctrl)  # reset simulation

    sim.input['attendance'] = att_score
    sim.input['assignments'] = assign_score
    sim.input['participation'] = part_score

    sim.compute()

    perf_score = sim.output['performance']

    # Interpretation
    if perf_score < 40:
        interpretation = "Needs Improvement"
    elif perf_score < 70:
        interpretation = "Satisfactory"
    elif perf_score < 90:
        interpretation = "Good"
    else:
        interpretation = "Excellent"

    return perf_score, interpretation

# ---------------------------------------------------
# 5. Sample Runs
# ---------------------------------------------------

if __name__ == "__main__":

    print("\nCase 1: Weak Performer")
    s1, i1 = evaluate_student(55, 60, 3)
    print(f"Performance Score: {s1:.1f}% → {i1}")

    print("\nCase 2: Average Student")
    s2, i2 = evaluate_student(75, 72, 6)
    print(f"Performance Score: {s2:.1f}% → {i2}")

    print("\nCase 3: High Achiever")
    s3, i3 = evaluate_student(92, 88, 9)
    print(f"Performance Score: {s3:.1f}% → {i3}")

    # Optional plots
    if input("\nShow membership function plots? (y/n): ").lower() == 'y':
        attendance.view()
        assignments.view()
        participation.view()
        performance.view()
        plt.show()