# -*- coding: utf-8 -*-
"""ResultReproduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dhtqRXMzs0wbGTN3mTY7pbIhoMHz9DJ
"""

import numpy as np

# Create 1D array
arr = np.arange(3, 23)
print('1D Array:', arr)

# Reshape to 2x5 matrix
matrix = arr.reshape(2, 10)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(1, 21)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)