# -*- coding: utf-8 -*-
"""saifLab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpTv5OY8tHwx0ENi0n6OfLH0oMEW3zis
"""

# create a list of 10 integers
numbers = [10,23,5,89,45,67,34,11,90]
print('Original List:', numbers)

#sum, max, and min
print('Sum:', sum(numbers))
print('Max:', max(numbers))
print('Min:', min(numbers))

#Add and remove element
numbers.append(50)
numbers.remove(23)
print('Updated List:', numbers)

#sort ascending and decending
print('Ascending:', sorted (numbers))
print('Descending:', sorted (numbers, reverse=True))

#create a tuple with 5 strings
fruits = ('apple', 'banana', 'cherry', 'date', 'blueberry')
print('second element:', fruits[1])
print('Last element:', fruits[-1])

#modification in tuple by creating a list
fruits_list = list(fruits)
fruits_list[2] = 'grape'
print('Modified list:', fruits_list)

#creating two sets
set1 = {1,2,3,4,5}
set2 = {4,5,6,7,8}
print('Set1:', set1)
print('Set2:', set2)

#union, intersection, difference
print('Union:', set1.union(set2))
print('Intersection:', set1 & set2 )
print('Difference:', set1 - set2 )

#creating student keys through dictionary and print

student =  {'Saif': 100, 'zoraiz': 60, 'ali':85}
print('keys:', student.keys())
print('values:', student.values())